create table products (
	id INT,
	name VARCHAR(50),
	buying_price VARCHAR(50),
	selling_price VARCHAR(50)
);
insert into products (id, name, buying_price, selling_price) values (1, 'Waterproof Rain Boots', 69.99, 79.99);
insert into products (id, name, buying_price, selling_price) values (2, 'Outdoor Portable Fire Pit', 149.99, 159.99);
insert into products (id, name, buying_price, selling_price) values (3, 'Basketball', 29.99, 39.99);
insert into products (id, name, buying_price, selling_price) values (4, 'Active Racerback Tank', 24.99, 34.99);
insert into products (id, name, buying_price, selling_price) values (5, 'High-Low Hem Tee', 22.99, 32.99);
insert into products (id, name, buying_price, selling_price) values (6, 'Apricot Jam', 4.29, 14.29);
insert into products (id, name, buying_price, selling_price) values (7, 'Foldable Yoga Mat', 29.99, 39.99);
insert into products (id, name, buying_price, selling_price) values (8, 'Roasted Garlic Mashed Potatoes', 3.99, 13.99);
insert into products (id, name, buying_price, selling_price) values (9, 'Fitness Tracker Band', 29.99, 39.99);
insert into products (id, name, buying_price, selling_price) values (10, 'Inflatable Pool Float', 29.99, 39.99);
insert into products (id, name, buying_price, selling_price) values (11, 'Fishing Tackle Box', 24.99, 34.99);
insert into products (id, name, buying_price, selling_price) values (12, 'Phone Screen Protector', 12.99, 22.99);
insert into products (id, name, buying_price, selling_price) values (13, 'Folding Table', 59.99, 69.99);
insert into products (id, name, buying_price, selling_price) values (14, 'Nutty Granola Clusters', 2.49, 12.49);
insert into products (id, name, buying_price, selling_price) values (15, 'Maple Almond Granola', 5.49, 15.49);
insert into products (id, name, buying_price, selling_price) values (16, 'Sesame Ginger Dressing', 4.09, 14.09);
insert into products (id, name, buying_price, selling_price) values (17, 'Printed Maxi Skirt', 39.99, 49.99);
insert into products (id, name, buying_price, selling_price) values (18, 'LED Canopy Lights', 29.99, 39.99);
insert into products (id, name, buying_price, selling_price) values (19, 'Waffle Maker', 39.99, 49.99);
insert into products (id, name, buying_price, selling_price) values (20, 'Portable Refrigerator Freezer', 299.99, 309.99);
insert into products (id, name, buying_price, selling_price) values (21, 'Customizable Name Plate', 19.99, 29.99);
insert into products (id, name, buying_price, selling_price) values (22, 'Ranch Dressing', 2.59, 12.59);
insert into products (id, name, buying_price, selling_price) values (23, 'Chia Seeds', 6.99, 16.99);
insert into products (id, name, buying_price, selling_price) values (24, 'Peach & Mango Salsa', 4.49, 14.49);
insert into products (id, name, buying_price, selling_price) values (25, 'Vegetable Curry', 5.99, 15.99);
insert into products (id, name, buying_price, selling_price) values (26, 'Outdoor Camping Lantern', 34.99, 44.99);
insert into products (id, name, buying_price, selling_price) values (27, 'Beard Grooming Kit', 34.99, 44.99);
insert into products (id, name, buying_price, selling_price) values (28, 'Soft Plush Throw Blanket', 29.99, 39.99);
insert into products (id, name, buying_price, selling_price) values (29, 'Almond Flour Cookies', 4.99, 14.99);
insert into products (id, name, buying_price, selling_price) values (30, 'Jasmine Rice', 2.39, 12.39);
insert into products (id, name, buying_price, selling_price) values (31, 'Travel Pillow', 22.99, 32.99);
insert into products (id, name, buying_price, selling_price) values (32, 'Snap-On Tupperware Set', 34.99, 44.99);
insert into products (id, name, buying_price, selling_price) values (33, 'Flavored Rice Cakes', 2.49, 12.49);
insert into products (id, name, buying_price, selling_price) values (34, 'Frozen Cauliflower Rice', 2.99, 12.99);
insert into products (id, name, buying_price, selling_price) values (35, 'Savory Oatmeal', 2.49, 12.49);
insert into products (id, name, buying_price, selling_price) values (36, 'Biodegradable Dog Waste Bags', 14.99, 24.99);
insert into products (id, name, buying_price, selling_price) values (37, 'Water-Resistant Bluetooth Speaker', 59.99, 69.99);
insert into products (id, name, buying_price, selling_price) values (38, 'Organic Spinach', 2.99, 12.99);
insert into products (id, name, buying_price, selling_price) values (39, 'Organic Black Bean Burger', 4.49, 14.49);
insert into products (id, name, buying_price, selling_price) values (40, 'Electric Heating Pad', 20.99, 30.99);
insert into products (id, name, buying_price, selling_price) values (41, 'Pet Grooming Scissors', 16.99, 26.99);
insert into products (id, name, buying_price, selling_price) values (42, 'Sriracha Hot Chili Sauce', 2.99, 12.99);
insert into products (id, name, buying_price, selling_price) values (43, 'Portable Pet Pooper Scooper', 12.99, 22.99);
insert into products (id, name, buying_price, selling_price) values (44, 'Travel Hair Straightener', 29.99, 39.99);
insert into products (id, name, buying_price, selling_price) values (45, 'Electric Rice Cooker', 39.99, 49.99);
insert into products (id, name, buying_price, selling_price) values (46, 'Electric Kettle', 39.99, 49.99);
insert into products (id, name, buying_price, selling_price) values (47, 'Pet Food Storage Container', 24.99, 34.99);
insert into products (id, name, buying_price, selling_price) values (48, 'Ethically-Sourced Coffee Beans', 9.99, 19.99);
insert into products (id, name, buying_price, selling_price) values (49, 'Multifunctional Pocket Tool', 19.99, 29.99);
insert into products (id, name, buying_price, selling_price) values (50, 'Organic Green Lentils', 3.99, 13.99);
insert into products (id, name, buying_price, selling_price) values (51, 'Organic Whole Grain Oats', 2.49, 12.49);
insert into products (id, name, buying_price, selling_price) values (52, 'Pest Control Traps', 22.99, 32.99);
insert into products (id, name, buying_price, selling_price) values (53, 'Herbed Couscous', 2.49, 12.49);
insert into products (id, name, buying_price, selling_price) values (54, 'Reclining Camping Chair', 49.99, 59.99);
insert into products (id, name, buying_price, selling_price) values (55, 'Smartphone Stand', 15.49, 25.49);
insert into products (id, name, buying_price, selling_price) values (56, 'Reversible Comforter Set', 89.99, 99.99);
insert into products (id, name, buying_price, selling_price) values (57, 'Outdoor Portable Fire Pit', 149.99, 159.99);
insert into products (id, name, buying_price, selling_price) values (58, 'USB Flash Drive', 9.99, 19.99);
insert into products (id, name, buying_price, selling_price) values (59, 'Peach Mango Smoothie', 3.49, 13.49);
insert into products (id, name, buying_price, selling_price) values (60, 'Marinara Parmesan Baked Ziti', 8.49, 18.49);
insert into products (id, name, buying_price, selling_price) values (61, 'Ceramic Planter Set', 39.99, 49.99);
insert into products (id, name, buying_price, selling_price) values (62, 'Spinach and Feta Stuffed Chicken Breast', 8.99, 18.99);
insert into products (id, name, buying_price, selling_price) values (63, 'Snap-On Tupperware Set', 34.99, 44.99);
insert into products (id, name, buying_price, selling_price) values (64, 'Oven Mitts with Pocket', 19.99, 29.99);
insert into products (id, name, buying_price, selling_price) values (65, 'Ultra-Thin Laptop Sleeve', 19.99, 29.99);
insert into products (id, name, buying_price, selling_price) values (66, 'Instant Camera', 89.99, 99.99);
insert into products (id, name, buying_price, selling_price) values (67, 'Organic Whole Wheat Flour', 2.99, 12.99);
insert into products (id, name, buying_price, selling_price) values (68, 'Sun-Dried Tomatoes', 3.99, 13.99);
insert into products (id, name, buying_price, selling_price) values (69, 'Chocolate Peanut Butter Cups', 2.29, 12.29);
insert into products (id, name, buying_price, selling_price) values (70, 'Pumpkin Waffles', 4.49, 14.49);
insert into products (id, name, buying_price, selling_price) values (71, 'Spicy Italian Sausage', 4.99, 14.99);
insert into products (id, name, buying_price, selling_price) values (72, 'Camping Tent', 79.99, 89.99);
insert into products (id, name, buying_price, selling_price) values (73, 'Digital Bullet Journal', 24.99, 34.99);
insert into products (id, name, buying_price, selling_price) values (74, 'Multi-Purpose Marine Rope', 19.99, 29.99);
insert into products (id, name, buying_price, selling_price) values (75, 'Fleece Hoodie', 39.99, 49.99);
insert into products (id, name, buying_price, selling_price) values (76, 'Steak Seasoning Rub', 2.49, 12.49);
insert into products (id, name, buying_price, selling_price) values (77, 'Pet Hair Vacuum Attachment', 14.99, 24.99);
insert into products (id, name, buying_price, selling_price) values (78, 'Fleece Throw Blanket', 29.99, 39.99);
insert into products (id, name, buying_price, selling_price) values (79, 'Vintage Button-Down Shirt', 45.99, 55.99);
insert into products (id, name, buying_price, selling_price) values (80, 'Dried Apricots', 3.79, 13.79);
insert into products (id, name, buying_price, selling_price) values (81, 'Maple Syrup', 6.99, 16.99);
insert into products (id, name, buying_price, selling_price) values (82, 'Caramel Apple Taffy', 1.99, 11.99);
insert into products (id, name, buying_price, selling_price) values (83, 'Electric Knife', 39.99, 49.99);
insert into products (id, name, buying_price, selling_price) values (84, 'Outdoor Camping Lantern', 34.99, 44.99);
insert into products (id, name, buying_price, selling_price) values (85, 'Nature Explorer Lens Kit', 19.99, 29.99);
insert into products (id, name, buying_price, selling_price) values (86, 'Backpack', 49.99, 59.99);
insert into products (id, name, buying_price, selling_price) values (87, 'Cable Knit Cardigan', 49.99, 59.99);
insert into products (id, name, buying_price, selling_price) values (88, 'Coconut Milk Yogurt', 2.99, 12.99);
insert into products (id, name, buying_price, selling_price) values (89, 'Bike Helmet', 34.99, 44.99);
insert into products (id, name, buying_price, selling_price) values (90, 'Smart Plug', 19.99, 29.99);
insert into products (id, name, buying_price, selling_price) values (91, 'Marinara Parmesan Baked Ziti', 8.49, 18.49);
insert into products (id, name, buying_price, selling_price) values (92, 'LED Christmas Lights', 29.99, 39.99);
insert into products (id, name, buying_price, selling_price) values (93, 'Tea Infuser', 12.99, 22.99);
insert into products (id, name, buying_price, selling_price) values (94, 'Cinnamon Sugar Popcorn', 2.89, 12.89);
insert into products (id, name, buying_price, selling_price) values (95, 'Frozen Vegetarian Pizza', 6.49, 16.49);
insert into products (id, name, buying_price, selling_price) values (96, 'Electrolyte Water Bottle', 34.99, 44.99);
insert into products (id, name, buying_price, selling_price) values (97, 'Rolling Cooler', 59.99, 69.99);
insert into products (id, name, buying_price, selling_price) values (98, 'Savory Quinoa Pudding', 2.99, 12.99);
insert into products (id, name, buying_price, selling_price) values (99, 'Avocados', 1.5, 11.5);
insert into products (id, name, buying_price, selling_price) values (100, 'Mini Meatballs', 5.99, 15.99);
